### ISSUE TITLE
docker run --link postgres:db ... --d dcm4che/dcm4chee-arc-psql invalid reference format

### ISSUE THREAD

**Issue by yongliangZhang** [dcm4che-dockerfiles/postgres-dcm4chee#1]
``[root@localhost ~]# docker run --link postgres:db ... --d dcm4che/dcm4chee-arc-psql
docker: invalid reference format.
See 'docker run --help'.
```
```
[root@localhost ~]# docker ps
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS                    NAMES
2b64d913e429        dcm4che/postgres-dcm4chee:10.0-12   "docker-entrypoint.s…"   4 minutes ago       Up 4 minutes        0.0.0.0:5432->5432/tcp   postgres
```
I have started the container, but I can't create a connection. Can you tell me what to ask? thank you very much

**Comment by gunterze** [comment]
Using --link is deprecated. Use --network instead. See [Run minimum set of archive services on a single host](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Run-minimum-set-of-archive-services-on-a-single-host). Please use the [user forum](https://groups.google.com/forum/#!forum/dcm4che) and not the issue tracker for such questions.
