### ISSUE TITLE
Manifest unknown

### ISSUE THREAD

**Issue by ramonribeiro96** [dcm4che-dockerfiles/postgres-dcm4chee#5]
Hi, I went to pull the docker and the error appeared:

`# docker pull dcm4che/postgres-dcm4chee`
```
Using default tag: latest
Error response from daemon: manifest for dcm4che/postgres-dcm4chee:latest not found: manifest unknown: manifest unknown

```

is it bug?

**Comment by gunterze** [comment]
There is no tag latest. Available tags: https://hub.docker.com/repository/docker/dcm4che/postgres-dcm4chee/tags

The suffix of the tag must match with the archive version, e.g. "-21" for archive 5.21.0.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
